### ISSUE TITLE
Reset terminal color via ANSI reset

### ISSUE THREAD

**Issue by freon27** [supertokens/browser-tabs-lock#11]
Is it possible that you're not resetting the terminal colour after you switch to yellow in the post-install script?  

It doesn't seen to be a problem with a terminal install but on Jenkins it turns the rest of our log yellow and makes it very hard to read: 

![image](https://user-images.githubusercontent.com/375694/86592507-e7e71400-bf93-11ea-8af2-7ea6d5c2a839.png)

Thanks
Nick

**Comment by freon27** [comment]
Thanks! :)

**Comment by rishabhpoddar** [comment]
Thanks for pointing it out :)
