### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by luisrudge** [supertokens/browser-tabs-lock#2]
Hi friends! Loved the project. Any chance you can publish an ES5 version of this for the poor souls like me that need to support IE11? 😝  Let me know how I can help with that 🎉

**Comment by nkshah2** [comment]
Glad to know you like our work! ES5 is a fair ask and we will start work on it.

**Comment by nkshah2** [comment]
ES5 support landed in 1.1.9. Feel free to reopen the issue if you run into anything else related.

**Comment by luisrudge** [comment]
wow. so fast! thanks @nkshah2 ❤️
