### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by ptomaszi** [supertokens/browser-tabs-lock#8]
Our React application has a dependency on the "browser-tabs-lock" package and recently our Jest tests have started to fail with the following error:

```
E:\git\ScionUi\node_modules\browser-tabs-lock\processLock.ts:2
        static instance: undefined | ProcessLocking;
    SyntaxError: Unexpected strict mode reserved word

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/browser-tabs-lock/index.js:38:21)
```

Looking into the "processLock.ts" file it complains about the use of "static" in the "ProcessLocking" class:

```
class ProcessLocking {
    static instance: undefined | ProcessLocking;
    private locked: Map<string, (() => void)[]> = new Map<string, (() => void)[]>();
```

Can someone provide a solution to that issue or provide some workaround?

**Comment by nkshah2** [comment]
The issue with .ts files has been resolved in the latest version of browser-tabs-lock. I recommend upgrading to the latest version and verifying if the issue still persists.

Note: If you are using auth0-spa-js simply running ```npm i``` should resolve the issue. 

Let us know if the issue persists on the latest version (1.2.5 at the time of writing this).

**Comment by ptomaszi** [comment]
We use "@auth0/auth0-spa-js": "^1.6.0" and it is still an issue.

Hovewer installing "browser-tabs-lock" dependency manually to the latest version resolves the issue.

Is that a problem that "@auth0/auth0-spa-js" packages has not got the latest version of "browser-tabs-lock"?

**Comment by nkshah2** [comment]
Can you try running ```npm update``` instead. This should fetch the latest version.

**Comment by nkshah2** [comment]
Closing this issue since there has been no update on the situation for a while
